In [2]:
import pandas as pd
import requests

url  = 'https://orchestrator.pgatour.com/graphql'

payload = {"operationName":"PlayerDirectory","variables":{"tourCode":"R"},"query":"query PlayerDirectory($tourCode: TourCode!, $active: Boolean) {\n  playerDirectory(tourCode: $tourCode, active: $active) {\n    tourCode\n    players {\n      id\n      isActive\n      firstName\n      lastName\n      shortName\n      displayName\n      alphaSort\n      country\n      countryFlag\n      headshot\n      playerBio {\n        id\n        age\n        education\n        turnedPro\n      }\n    }\n  }\n}"}

response = requests.post(url, json = payload, headers = {'X-Api-Key':
'da2-gsrx5bibzbb4njvhl7t37wqyl4'}
)

results = response.json()

player_name = []
player_id = []
player_nationality = []


for player in results['data']['playerDirectory']['players']:
    player_name.append(player['displayName'])
    player_id.append(player['id'])
    player_nationality.append(player['countryFlag'])

In [4]:
data = {'player_name': player_name,
        'player_id' : player_id,
        'player_nationality' : player_nationality}

df = pd.DataFrame(data)
df

           player_name player_id player_nationality
0          Tommy Aaron     01001                USA
1         Jerry Abbott     12855
2           Pat Abbott     12856
3         Bob Ackerman     01003                USA
4      Joe Acosta, Jr.     20051                USA
...                ...       ...                ...
2433   Emery Zimmerman     19743
2434  Robert Zimmerman     09025                USA
2435      Billy Ziobro     08625                USA
2436     Fuzzy Zoeller     02321                USA
2437     Richard Zokol     02322                CAN

[2438 rows x 3 columns]

In [5]:
df.to_csv('/users/zack burnside/desktop/player_db.csv')